# wrangler.toml
name = 'calm-pine-933a'
main = "src/worker.js"
compatibility_date = "2026-04-21"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "apitest_bind"
database_name = "apitest"
database_id = "5f155f13-2487-47b8-a436-eb660b552a93"
